### ISSUE TITLE
Siapa aku?

### ISSUE THREAD

**Issue by emiralrashid** [ratabb/tempatbermain#2]
Tempatnya di mana kang? wkwk

**Comment by ratabb** [comment]
Pertanyaan yang bagus, untuk saat ini belum bisa dijawab.

huehue.

**Comment by ratabb** [comment]
@emiralrashid kang, buatin halaman buat hishoot2i atuh, *hiks*
ta inpit ke grup/org hishoot di github mau yah?

**Comment by emiralrashid** [comment]
Grid atau gimana kang? Aktif di telegram ngak?

**Comment by ratabb** [comment]
mbuh ra reti kang. ay baru buat tempatnya aja [disini](https://github.com/hishoot2i/hishoot2i.github.io)

tele ay blom main.

**Comment by ratabb** [comment]
check pm di hangouts kang.
